/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import civitas.CivitasJuego;
import civitas.OperacionesJuego;
import javax.swing.JOptionPane;
import civitas.Respuestas;
import civitas.SalidasCarcel;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

/**
 *
 * @author thejoker
 */
public class CivitasView extends javax.swing.JFrame {
    private CivitasJuego juego;
    private GestionarDialog gestionarD;
    
    /**
     * Creates new form CivitasView
     */
    public CivitasView() {
        initComponents();
        repaint();
        revalidate();
    }

    public void actualizarVista() {
        this.jugadorPanel.setJugador(juego.getJugadorActual());
        this.casillaPanel.setCasilla(juego.getCasillaActual());
        repaint();
        this.setVisible(true);
    }
    
    public void setCivitasJuego(CivitasJuego civitas) {
        juego = civitas;
        new CivitasView().setVisible(true);
    }
    
    public void mostrarSiguienteOperacion(OperacionesJuego operacion) {
        ArrayList<String> operaciones = new ArrayList<>(Arrays.asList(
                "Avanzar", "Comprar", "Gestionar", "Salir de la carcel",
                "Pasar el turno"
        ));
        
        int indice = 4;
        
        switch (operacion) {
            case AVANZAR:
                indice = 0;
                break;
            case COMPRAR:
                indice = 1;
                break;
            case GESTIONAR:
                indice = 2;
                break;
            case SALIR_CARCEL:
                indice = 3;
                break;
        }
        
        operacionLabel.setText(operaciones.get(indice));
        this.actualizarVista();
    }
    
    void mostrarEventos() {
        DiarioDialog diarioD = new DiarioDialog(this, true); // crear la ventana del 
        diarioD.repaint();
        diarioD.revalidate();
    }
    
    Respuestas comprar() {
        int opcion = JOptionPane.showConfirmDialog(null, "¿Quieres comprar la calle actual?", 
                "Comprar", JOptionPane.YES_NO_OPTION);
        
        return (Respuestas.values()[opcion]);
    }
    
    SalidasCarcel salirCarcel() {
        String[] opciones= {"Pagando", "Tirando"};
        
        int respuesta= JOptionPane.showOptionDialog(null, "¿Cómo quieres salir de la cárcel?",
        "Salir de la cárcel", JOptionPane.DEFAULT_OPTION,
        JOptionPane.QUESTION_MESSAGE,null, opciones, opciones[0] );
        
        return (SalidasCarcel.values()[respuesta]);
    }
    
    void gestionar() {
        pack();
        repaint();
        revalidate();
        gestionarD.gestionar(juego.getJugadorActual());
        gestionarD.setVisible(true);
    }
    
    public int getGestion() {
        return this.gestionarD.getGestion();
    }
    
    public int getPropiedad() {
        return this.gestionarD.getPropiedad();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jugadorPanel = new GUI.JugadorPanel();
        casillaPanel = new GUI.CasillaPanel();
        jPanel1 = new javax.swing.JPanel();
        operacionLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(50, 50));
        getContentPane().add(jugadorPanel, java.awt.BorderLayout.LINE_END);
        getContentPane().add(casillaPanel, java.awt.BorderLayout.CENTER);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        operacionLabel.setText("Ninguna operacion");
        operacionLabel.setToolTipText("operacion");
        jPanel1.add(operacionLabel);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CivitasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CivitasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CivitasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CivitasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new CivitasView().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private GUI.CasillaPanel casillaPanel;
    private javax.swing.JPanel jPanel1;
    private GUI.JugadorPanel jugadorPanel;
    private javax.swing.JLabel operacionLabel;
    // End of variables declaration//GEN-END:variables
}
