/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import civitas.Jugador;
import civitas.TituloPropiedad;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.DefaultListModel;

/**
 *
 * @author thejoker
 */
public class GestionarDialog extends javax.swing.JDialog {
    int gestionElegida;
    int propiedadElegida;
    
    
    /**
     * Creates new form GestionarDialog
     */
    public GestionarDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        
        gestionElegida = -1;
        propiedadElegida = -1;
    }

    public int getGestion() {
        return this.gestionElegida;
    }
    
    public int getPropiedad() {
        return this.propiedadElegida;
    }
    
    public void setGestiones() {
        DefaultListModel gestiones = new DefaultListModel<>();
        ArrayList<String> opciones = new ArrayList<>(Arrays.asList(
           "Vender", "Hipotecar", "Cancelar hipoteca", 
           "Construir casa", "Construir hotel",
           "Terminar"
        ));
        
        for (String s: opciones) {
            gestiones.addElement(s);
        }
        
        listaGestiones.setModel(gestiones);
    }
    
    public void setPropiedades(Jugador jugador) {
        DefaultListModel propiedades = new DefaultListModel<>();

        for (TituloPropiedad t : jugador.getPropiedades()) {
            propiedades.addElement(t.getNombre());
        }

        listaPropiedades.setModel(propiedades);
    }
    
    public void gestionar(Jugador jugador) {
        setGestiones();
        setPropiedades(jugador);
        repaint();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        gestionesPane = new javax.swing.JScrollPane();
        listaGestiones = new javax.swing.JList<>();
        jSeparator2 = new javax.swing.JSeparator();
        propiedadesPane = new javax.swing.JScrollPane();
        listaPropiedades = new javax.swing.JList<>();
        jPanel5 = new javax.swing.JPanel();
        realizarButton = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Gestiones"));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setText("Lista de Gestiones");
        jPanel3.add(jLabel1);
        jPanel3.add(jSeparator1);

        jLabel2.setText("lista de Propiedades");
        jPanel3.add(jLabel2);

        jPanel1.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        gestionesPane.setPreferredSize(new java.awt.Dimension(150, 200));

        listaGestiones.setLayoutOrientation(javax.swing.JList.HORIZONTAL_WRAP);
        listaGestiones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaGestionesMouseClicked(evt);
            }
        });
        gestionesPane.setViewportView(listaGestiones);

        jPanel4.add(gestionesPane);
        jPanel4.add(jSeparator2);

        propiedadesPane.setPreferredSize(new java.awt.Dimension(150, 200));

        listaPropiedades.setLayoutOrientation(javax.swing.JList.HORIZONTAL_WRAP);
        listaPropiedades.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaPropiedadesMouseClicked(evt);
            }
        });
        propiedadesPane.setViewportView(listaPropiedades);

        jPanel4.add(propiedadesPane);

        jPanel1.add(jPanel4, java.awt.BorderLayout.CENTER);

        realizarButton.setText("Realizar");
        realizarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                realizarButtonActionPerformed(evt);
            }
        });
        jPanel5.add(realizarButton);

        jPanel1.add(jPanel5, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void realizarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_realizarButtonActionPerformed
        if (this.gestionElegida != -1 && this.propiedadElegida != -1) {
            gestionElegida = listaGestiones.getSelectedIndex();
            propiedadElegida = listaPropiedades.getSelectedIndex();
            dispose();
        }
    }//GEN-LAST:event_realizarButtonActionPerformed

    private void listaGestionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaGestionesMouseClicked
        gestionElegida = listaGestiones.getSelectedIndex();
    }//GEN-LAST:event_listaGestionesMouseClicked

    private void listaPropiedadesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaPropiedadesMouseClicked
        propiedadElegida = listaPropiedades.getSelectedIndex();
    }//GEN-LAST:event_listaPropiedadesMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane gestionesPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JList<String> listaGestiones;
    private javax.swing.JList<String> listaPropiedades;
    private javax.swing.JScrollPane propiedadesPane;
    private javax.swing.JButton realizarButton;
    // End of variables declaration//GEN-END:variables
}
